### Exercise

A. Create an ndarry object (A) with any values from 1 to 100 in a nested Python List. You can choose your range from the given values (1-100).

* Given that A is an ndarray object, many functionalities in numpy could be accessed by:
    + Make sure to explain each line of codes that you have created.

1. Using a property of the ndarray object
      - e.g. `A.shape`
2. Using a method of the ndarray object
      - e.g. `A.max()`
3. Using a numpy function and passing an ndarray
     - e.g. `np.max(A)`

B. Create a 5x5 integer-array filled with ones.
* Check its shape, size, and number of dimensions. Explain briefly the codes you have created by writing a comment beside the code.

C. Create an array of values from -5 to + 5. Multiply each value with 2. Print the resulting array.

In [14]:
import numpy as np

A = np.array([[5, 10, 15], [20, 25, 30]])  # Creating a 2D array using a nested list with values from 1–100

print("Shape:",A.shape)   # Using a property to get the structure of the array
print("max:",A.max())   # Using a method of the array to get the maximum value
print("max(A):",np.max(A)) # Using a NumPy function to get the maximum value

Shape: (2, 3)
max: 30
max(A): 30


In [13]:
B = np.ones((5, 5), dtype=int)  # Creates a 5x5 array filled with integer 1s

print(B)        # Displays the array
print("Shape:",B.shape)  # Shows the array has 5 rows and 5 columns
print("Size:", B.size)   # Shows the total number of elements (25)
print("NDim:", B.ndim)   # Shows the number of dimensions (2D array)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
Shape: (5, 5)
Size: 25
NDim: 2


In [7]:
C = np.arange(-5, 6)  # Creates values starting from -5 up to 5
C = C * 2             # Multiplies each value in the array by 2

print(C)              # Displays the final array

[-10  -8  -6  -4  -2   0   2   4   6   8  10]
